// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThemeParkManagementSystem.Services.DataContext;

#nullable disable

namespace ThemeParkManagementSystem.Services.Migrations
{
    [DbContext(typeof(TPMSDbContext))]
    [Migration("20251130052739_moreseeds")]
    partial class moreseeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("ThemeParkManagementSystem.Entities.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextMaintenance")
                        .HasColumnType("TEXT");

                    b.Property<int>("WaitTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 24,
                            Description = "High-speed roller coaster",
                            Name = "Dragon Coaster",
                            NextMaintenance = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 45
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20,
                            Description = "Log flume ride with drops",
                            Name = "Splash Mountain",
                            NextMaintenance = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 30
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 40,
                            Description = "Giant ferris wheel with views",
                            Name = "Sky Wheel",
                            NextMaintenance = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 15
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 16,
                            Description = "Dark ride with animatronics",
                            Name = "Haunted Mansion",
                            NextMaintenance = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 25
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 12,
                            Description = "Vertical launch thrill ride",
                            Name = "Rocket Launch",
                            NextMaintenance = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 60
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 30,
                            Description = "Boat safari adventure",
                            Name = "Jungle Expedition",
                            NextMaintenance = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 40
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 28,
                            Description = "Water boat battle ride",
                            Name = "Pirate Bay",
                            NextMaintenance = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 35
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 18,
                            Description = "Spinning space-themed ride",
                            Name = "Galactic Spin",
                            NextMaintenance = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 20
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 25,
                            Description = "Fast-paced river rafting",
                            Name = "Wild River Rapids",
                            NextMaintenance = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 55
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 22,
                            Description = "Indoor mine-cart roller coaster",
                            Name = "Mystery Mine",
                            NextMaintenance = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 50
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 40,
                            Description = "Aerial gondola with aerial views",
                            Name = "Sky Glider",
                            NextMaintenance = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 10
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 14,
                            Description = "Extreme spinning thrill ride",
                            Name = "Tornado Twister",
                            NextMaintenance = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 65
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 16,
                            Description = "Tower drop ride",
                            Name = "Firestorm Drop",
                            NextMaintenance = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 70
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 50,
                            Description = "Classic carousel with fantasy theme",
                            Name = "Enchanted Carousel",
                            NextMaintenance = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 5
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 30,
                            Description = "Motion simulator space ride",
                            Name = "Cosmic Cruiser",
                            NextMaintenance = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 45
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 20,
                            Description = "Dark ride through frozen tunnels",
                            Name = "Ice Cavern Escape",
                            NextMaintenance = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 25
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 18,
                            Description = "High-speed volcanic themed coaster",
                            Name = "Volcano Surge",
                            NextMaintenance = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 90
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 14,
                            Description = "Sci-fi dark ride with animatronics",
                            Name = "Alien Encounter",
                            NextMaintenance = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 35
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 12,
                            Description = "Zip-line glider attraction",
                            Name = "Jungle Flyers",
                            NextMaintenance = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 80
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 20,
                            Description = "Slow exploration dark ride",
                            Name = "Crystal Caverns",
                            NextMaintenance = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 18
                        });
                });

            modelBuilder.Entity("ThemeParkManagementSystem.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePurchased")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValidOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatePurchased = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Johnson",
                            Price = 59.99f,
                            Type = 0,
                            ValidOn = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DatePurchased = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bobby Smith",
                            Price = 39.99f,
                            Type = 1,
                            ValidOn = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DatePurchased = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Caroline Park",
                            Price = 149.99f,
                            Type = 3,
                            ValidOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DatePurchased = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "David Nguyen",
                            Price = 299.99f,
                            Type = 4,
                            ValidOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DatePurchased = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emily Carter",
                            Price = 29.99f,
                            Type = 5,
                            ValidOn = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            DatePurchased = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Franklin West",
                            Price = 59.99f,
                            Type = 0,
                            ValidOn = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            DatePurchased = new DateTime(2025, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grace Howard",
                            Price = 149.99f,
                            Type = 3,
                            ValidOn = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            DatePurchased = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Henry Lopez",
                            Price = 39.99f,
                            Type = 1,
                            ValidOn = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            DatePurchased = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Isabella Turner",
                            Price = 29.99f,
                            Type = 5,
                            ValidOn = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            DatePurchased = new DateTime(2025, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jacob Hill",
                            Price = 59.99f,
                            Type = 0,
                            ValidOn = new DateTime(2025, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            DatePurchased = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kelly Green",
                            Price = 49.99f,
                            Type = 2,
                            ValidOn = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            DatePurchased = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Liam Roberts",
                            Price = 59.99f,
                            Type = 0,
                            ValidOn = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            DatePurchased = new DateTime(2025, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mia Douglas",
                            Price = 149.99f,
                            Type = 3,
                            ValidOn = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            DatePurchased = new DateTime(2025, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Noah Carter",
                            Price = 39.99f,
                            Type = 1,
                            ValidOn = new DateTime(2025, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            DatePurchased = new DateTime(2025, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Olivia Brooks",
                            Price = 29.99f,
                            Type = 5,
                            ValidOn = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            DatePurchased = new DateTime(2025, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peter Winston",
                            Price = 59.99f,
                            Type = 0,
                            ValidOn = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            DatePurchased = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Quinn Adams",
                            Price = 49.99f,
                            Type = 2,
                            ValidOn = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            DatePurchased = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rebecca Miles",
                            Price = 149.99f,
                            Type = 3,
                            ValidOn = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            DatePurchased = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samuel Pratt",
                            Price = 39.99f,
                            Type = 1,
                            ValidOn = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            DatePurchased = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tiffany Rhodes",
                            Price = 29.99f,
                            Type = 5,
                            ValidOn = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            DatePurchased = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Franklin Moore",
                            Price = 59.99f,
                            Type = 0,
                            ValidOn = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            DatePurchased = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Georgia Alvarez",
                            Price = 39.99f,
                            Type = 1,
                            ValidOn = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            DatePurchased = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Henry Thompson",
                            Price = 29.99f,
                            Type = 5,
                            ValidOn = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
