// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThemeParkManagementSystem.Services.DataContext;

#nullable disable

namespace ThemeParkManagementSystem.Services.Migrations
{
    [DbContext(typeof(TPMSDbContext))]
    [Migration("20251129221617_seededdatabase2")]
    partial class seededdatabase2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("ThemeParkManagementSystem.Entities.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextMaintenance")
                        .HasColumnType("TEXT");

                    b.Property<int>("WaitTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 24,
                            Description = "High-speed roller coaster",
                            Name = "Dragon Coaster",
                            NextMaintenance = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 45
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20,
                            Description = "Log flume ride with drops",
                            Name = "Splash Mountain",
                            NextMaintenance = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 30
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 40,
                            Description = "Giant ferris wheel with views",
                            Name = "Sky Wheel",
                            NextMaintenance = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 15
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 16,
                            Description = "Dark ride with animatronics",
                            Name = "Haunted Mansion",
                            NextMaintenance = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 25
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 12,
                            Description = "Vertical launch thrill ride",
                            Name = "Rocket Launch",
                            NextMaintenance = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WaitTime = 60
                        });
                });

            modelBuilder.Entity("ThemeParkManagementSystem.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePurchased")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValidOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatePurchased = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adult Day Pass",
                            Price = 59.99f,
                            Type = 0,
                            ValidOn = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DatePurchased = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Child Day Pass",
                            Price = 39.99f,
                            Type = 1,
                            ValidOn = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DatePurchased = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VIP Access",
                            Price = 149.99f,
                            Type = 3,
                            ValidOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DatePurchased = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Season Pass",
                            Price = 299.99f,
                            Type = 4,
                            ValidOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DatePurchased = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fast Pass",
                            Price = 29.99f,
                            Type = 5,
                            ValidOn = new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
